/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diarybook;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Maulana Alirridlo
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        if(!core.isLogin){
            this.dispose();
            new login().setVisible(true);
        }
        initComponents();
        
        new AutoResizeTable().setColumnWidth(tDiary);
        tDiary.revalidate();
        
        Dimension screenSz = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSz = this.getSize();
        setLocation((screenSz.width-frameSz.width)/2,(screenSz.height-frameSz.height)/2);
        
        Tampil.removeAll();
        Tampil.add(tambah);
        Tampil.repaint();
        Tampil.revalidate();
        tambahInitCond();
    }
    
    void tambahInitCond(){
        addTanggal.setDate(new Date());
        addJudul.setText("");
        addKegiatan.setText("");
    }
    
    void viewAllInitCond(){
        tDiary.setModel(core.getTabelDiary());
        tDiary.removeColumn(tDiary.getColumnModel().getColumn(0));
        viewDiary.setEnabled(false);
    }
    
    void pengaturanInitCond(){
        settingUsername.setText(core.username);
        settingPassword.setText(core.password);
        tampilPass.setText("Tampilkan Password");
        settingPassword.setEchoChar('*');
    }
    
    void showDiaryInitCond(){
        showTitle.setEnabled(false);
        showTanggal.setEnabled(false);
        showContent.setEnabled(false);
        
        showTitle.setText(core.showTitle);
        showTanggal.setDate(core.showTanggal);
        showContent.setText(core.showContent);
        showContent.setLineWrap(true);
        showContent.setWrapStyleWord(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Tampil = new javax.swing.JPanel();
        tambah = new javax.swing.JPanel();
        addTanggal = new com.toedter.calendar.JDateChooser();
        addJudul = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        addKegiatan = new javax.swing.JTextPane();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        viewAll = new javax.swing.JPanel();
        searchDate = new com.toedter.calendar.JDateChooser();
        jButton4 = new javax.swing.JButton();
        sDiary = new javax.swing.JScrollPane();
        tDiary = new javax.swing.JTable();
        viewDiary = new javax.swing.JButton();
        pengaturan = new javax.swing.JPanel();
        settingUsername = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        settingPassword = new javax.swing.JPasswordField();
        tampilPass = new javax.swing.JCheckBox();
        showDiary = new javax.swing.JPanel();
        showTitle = new javax.swing.JTextField();
        editDiary = new javax.swing.JButton();
        deleteDiary = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        showContent = new javax.swing.JTextArea();
        showTanggal = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 400));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(588, 381));

        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("pengaturan");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("tambah");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
        );

        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("viewAll");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );

        Tampil.setPreferredSize(new java.awt.Dimension(482, 381));
        Tampil.setLayout(new java.awt.CardLayout());

        tambah.setPreferredSize(new java.awt.Dimension(482, 381));

        jScrollPane3.setViewportView(addKegiatan);

        jButton3.setText("Tambah");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setText("Tanggal");

        jLabel3.setText("Judul");

        jLabel6.setText("Kegiatan");

        javax.swing.GroupLayout tambahLayout = new javax.swing.GroupLayout(tambah);
        tambah.setLayout(tambahLayout);
        tambahLayout.setHorizontalGroup(
            tambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahLayout.createSequentialGroup()
                .addGroup(tambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tambahLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(addJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tambahLayout.createSequentialGroup()
                        .addGap(377, 377, 377)
                        .addComponent(jButton3))
                    .addGroup(tambahLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(tambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(addTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(tambahLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(tambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32))
        );
        tambahLayout.setVerticalGroup(
            tambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(8, 8, 8)
                .addComponent(addJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3))
        );

        Tampil.add(tambah, "card2");

        viewAll.setPreferredSize(new java.awt.Dimension(482, 381));

        jButton4.setText("cari");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        tDiary.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tDiary.setRowSelectionAllowed(true);
        tDiary.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tDiaryFocusGained(evt);
            }
        });
        sDiary.setViewportView(tDiary);

        viewDiary.setText("Lihat");
        viewDiary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDiaryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout viewAllLayout = new javax.swing.GroupLayout(viewAll);
        viewAll.setLayout(viewAllLayout);
        viewAllLayout.setHorizontalGroup(
            viewAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewAllLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(viewAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(viewDiary)
                    .addGroup(viewAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(sDiary, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(viewAllLayout.createSequentialGroup()
                            .addComponent(searchDate, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton4))))
                .addGap(20, 20, 20))
        );
        viewAllLayout.setVerticalGroup(
            viewAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewAllLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(viewAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewAllLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(searchDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(sDiary, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewDiary)
                .addContainerGap())
        );

        Tampil.add(viewAll, "card3");

        pengaturan.setPreferredSize(new java.awt.Dimension(482, 381));

        jLabel7.setText("Username");

        jLabel8.setText("Password");

        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tampilPass.setText("Tampil/Sembunyikan Password");
        tampilPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tampilPassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pengaturanLayout = new javax.swing.GroupLayout(pengaturan);
        pengaturan.setLayout(pengaturanLayout);
        pengaturanLayout.setHorizontalGroup(
            pengaturanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pengaturanLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pengaturanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pengaturanLayout.createSequentialGroup()
                        .addComponent(tampilPass)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(settingUsername, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                    .addComponent(settingPassword, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(53, 53, 53))
        );
        pengaturanLayout.setVerticalGroup(
            pengaturanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pengaturanLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(settingUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(settingPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tampilPass)
                .addGap(8, 8, 8)
                .addComponent(jButton1)
                .addContainerGap())
        );

        Tampil.add(pengaturan, "card4");

        showTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        editDiary.setText("Edit");
        editDiary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editDiaryActionPerformed(evt);
            }
        });

        deleteDiary.setText("Hapus");
        deleteDiary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteDiaryActionPerformed(evt);
            }
        });

        showContent.setColumns(20);
        showContent.setRows(5);
        jScrollPane1.setViewportView(showContent);

        showTanggal.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        javax.swing.GroupLayout showDiaryLayout = new javax.swing.GroupLayout(showDiary);
        showDiary.setLayout(showDiaryLayout);
        showDiaryLayout.setHorizontalGroup(
            showDiaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showDiaryLayout.createSequentialGroup()
                .addGroup(showDiaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(showDiaryLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(showTitle))
                    .addGroup(showDiaryLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, showDiaryLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(editDiary)
                        .addGap(5, 5, 5)
                        .addComponent(deleteDiary)))
                .addContainerGap())
            .addGroup(showDiaryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(showTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(186, Short.MAX_VALUE))
        );
        showDiaryLayout.setVerticalGroup(
            showDiaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showDiaryLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(showTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(showTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(showDiaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editDiary)
                    .addComponent(deleteDiary))
                .addContainerGap())
        );

        Tampil.add(showDiary, "card5");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Tampil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(Tampil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        Tampil.removeAll();
        Tampil.add(tambah);
        Tampil.repaint();
        Tampil.revalidate();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        Tampil.removeAll();
        Tampil.add(viewAll);
        viewAllInitCond();
        Tampil.repaint();
        Tampil.revalidate();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        Tampil.removeAll();
        Tampil.add(pengaturan);
        pengaturanInitCond();
        Tampil.repaint();
        Tampil.revalidate();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
        Tampil.removeAll();
        Tampil.add(tambah);
        Tampil.repaint();
        Tampil.revalidate();
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
        Tampil.removeAll();
        Tampil.add(viewAll);
        viewAllInitCond();
        Tampil.repaint();
        Tampil.revalidate();
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:
        Tampil.removeAll();
        Tampil.add(pengaturan);
        pengaturanInitCond();
        Tampil.repaint();
        Tampil.revalidate();
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        java.util.Date utilStartDate = addTanggal.getDate();
        java.sql.Date sqlStartDate = new java.sql.Date(utilStartDate.getTime());
        core.addDiary(addJudul.getText(), addKegiatan.getText(), sqlStartDate);
        tambahInitCond();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        java.util.Date utilStartDate = searchDate.getDate();
        java.sql.Date sqlStartDate = new java.sql.Date(utilStartDate.getTime());
        tDiary.setModel(core.searchTabelDiary(sqlStartDate));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tampilPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tampilPassActionPerformed
        // TODO add your handling code here:
        if(tampilPass.isSelected() ){
            tampilPass.setText("Sembunyikan Password");
            settingPassword.setEchoChar((char)0); 
        }else{
            tampilPass.setText("Tampilkan Password");
            settingPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_tampilPassActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(core.username == settingUsername.getText() && core.password == settingPassword.getText()){
            JOptionPane.showMessageDialog(null,"","Tidak ada data yang berubah",JOptionPane.INFORMATION_MESSAGE);
        }else{
            core.updateUser(settingUsername.getText(), settingPassword.getText());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tDiaryFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tDiaryFocusGained
        // TODO add your handling code here:
        viewDiary.setEnabled(true);
    }//GEN-LAST:event_tDiaryFocusGained

    private void viewDiaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDiaryActionPerformed
        // TODO add your handling code here:
        core.getDiaryById((String) tDiary.getModel().getValueAt(tDiary.getSelectedRow(),0));
        Tampil.removeAll();
        Tampil.add(showDiary);
        showDiaryInitCond();
        Tampil.repaint();
        Tampil.revalidate();
    }//GEN-LAST:event_viewDiaryActionPerformed

    private void editDiaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editDiaryActionPerformed
        // TODO add your handling code here:
        if(editDiary.getText() == "Edit"){
            editDiary.setText("Update");
            deleteDiary.setText("Batal");

            showTitle.setEnabled(true);
            showTanggal.setEnabled(true);
            showContent.setEnabled(true); 
        }else if (editDiary.getText() == "Update"){
            java.util.Date utilStartDate = showTanggal.getDate();
            java.sql.Date sqlStartDate = new java.sql.Date(utilStartDate.getTime());
            core.updateDiary(core.showId, showTitle.getText(), showContent.getText(), sqlStartDate);
            editDiary.setText("Edit");
            deleteDiary.setText("Hapus");
        }
    }//GEN-LAST:event_editDiaryActionPerformed

    private void deleteDiaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDiaryActionPerformed
        // TODO add your handling code here:
        if(deleteDiary.getText() == "Batal"){
            editDiary.setText("Edit");
            deleteDiary.setText("Hapus");

            showTitle.setEnabled(false);
            showTanggal.setEnabled(false);
            showContent.setEnabled(false); 
        }else if (deleteDiary.getText() == "Hapus"){
            core.deleteDiary(core.showId);
            Tampil.removeAll();
            Tampil.add(viewAll);
            viewAllInitCond();
            Tampil.repaint();
            Tampil.revalidate();
        }
    }//GEN-LAST:event_deleteDiaryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Tampil;
    private javax.swing.JTextField addJudul;
    private javax.swing.JTextPane addKegiatan;
    private com.toedter.calendar.JDateChooser addTanggal;
    private javax.swing.JButton deleteDiary;
    private javax.swing.JButton editDiary;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel pengaturan;
    private javax.swing.JScrollPane sDiary;
    private com.toedter.calendar.JDateChooser searchDate;
    private javax.swing.JPasswordField settingPassword;
    private javax.swing.JTextField settingUsername;
    private javax.swing.JTextArea showContent;
    private javax.swing.JPanel showDiary;
    private com.toedter.calendar.JDateChooser showTanggal;
    private javax.swing.JTextField showTitle;
    private javax.swing.JTable tDiary;
    private javax.swing.JPanel tambah;
    private javax.swing.JCheckBox tampilPass;
    private javax.swing.JPanel viewAll;
    private javax.swing.JButton viewDiary;
    // End of variables declaration//GEN-END:variables
}
